apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workload-cluster-1-kubeconfig
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: workload-cluster-1-kubeconfig
    creationPolicy: Owner
  data:
  - secretKey: value
    remoteRef:
      key: workload-cluster-1-kubeconfig
