apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  interval: 10s
  dependsOn:
  - name: istio-base
    namespace: flux-system
  - name: istiod
    namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: "1.28.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 10s
  values:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
