apiVersion: platform.example.com/v1alpha1
kind: XApplication
metadata:
  name: nginx-demo
  namespace: default
spec:
  parameters:
    appName: nginx-demo
    image: nginx:1.25
    replicas: 2
    port: 80
    targetCluster: workload-cluster-1
    namespace: demo-app
