apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 5s
  chart:
    spec:
      chart: kiali-server
      version: "2.20.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      interval: 5s
  values:
    auth:
      strategy: anonymous
    external_services:
      istio:
        url_service_version: http://istiod:15014/version
      prometheus:
        url: http://prometheus:9090
    server:
      web_root: /
      web_fqdn: kiali.local
