apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workload-cluster-1-apps
  namespace: flux-system
spec:
  interval: 10s
  path: "./flux-config/apps/workload-cluster-1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    configMapRef:
      name: workload-cluster-1-kubeconfig
  dependsOn:
  - name: infra-controllers
