apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eks-cluster
  labels:
    provider: aws
    service: eks
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XEKSCluster
  
  mode: Resources
  resources:
  - name: eks-cluster
    base:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: Cluster
      spec:
        forProvider:
          region: eu-central-1
          version: "1.34"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: metadata.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
